export const selectedConstants = {
  SET_AGE: 'SET_AGE_SUCCESS',
  SET_ALL: 'SET_ALL_SUCCESS',
  SET_SORT: 'SET_SORT_SUCCESS',
  SET_TERMS: 'SET_TERMS_SUCCESS',
  TOOGLE_ONE: 'SET_ANY_SUCCESS',
  SET_PAGE: 'SET_PAGE',
  SET_MEMBERS : 'SET_MEMBERS_SUCCESS'
};
